name: 'Docker Build Publish'
description: 'Docker BuildX action'
inputs:
  name:
    description: docker image build tag
    default: ${{ github.repository }}
  registry:
    description: docker registry
    default: ghcr.io
  build-dir:
    description: Docker build context
    default: '.'
  build-args:
    description: Docker build arguments
    required: false
    default: ''
  build-contexts:
    description: Additional Docker contexts
    required: false
    default: ''
  github_token:
    description: Github Container Registry access
runs:
  using: 'composite'
  steps:
  - id: meta
    name: Docker meta
    uses: docker/metadata-action@v4
    with:
      images: |
        ${{ inputs.registry }}/${{ inputs.name }}
      tags: |
        type=raw,value=latest
        type=ref,event=branch,suffix=-latest
        type=sha,prefix=,format=long
  - id: buildx
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
  - id: login
    name: Login to Github Container Registry
    shell: bash
    run: |
      echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  - id: build
    name: Build And Push
    uses: docker/build-push-action@v4
    with:
      context: ${{ inputs.build-dir }}
      file: ${{ inputs.build-dir }}/Dockerfile
      platforms: linux/amd64
      tags: ${{ steps.meta.outputs.tags }}
      push: true
      build-args: ${{ inputs.build-args }}
      build-contexts: ${{ inputs.build-contexts }}
outputs:
  image_url:
    description: full docker image url
    value: ${{ inputs.registry }}/${{ inputs.name }}:${{ steps.meta.outputs.version }}