name: 'Docker Build Publish'
description: 'Docker BuildX action'
inputs:
  name:
    description: Name of docker image build tag
  build-args:
    description: Docker build arguments
    required: false
    default: ''
  github_token:
    description: Github Container Registry access
runs:
  using: 'composite'
  steps:

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: |
        ghcr.io/${{ github.repository_owner }}/${{ inputs.name }}
      tags: |
        type=raw,value=latest
        type=ref,event=branch,suffix=-latest
        type=sha,prefix=,format=long
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Login to Github Container Registry
    id: login
    shell: bash
    run: |
      echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  - name: Build And Push
    id: build
    uses: docker/build-push-action@v2
    with:
      context: .
      file: Dockerfile
      platforms: linux/amd64
      tags: ${{ steps.meta.outputs.tags }}
      push: true
      build-args: ${{ inputs.build-args }}