name: 'Docker Build Publish'
description: 'Docker BuildX action'
inputs:
  container_name:
    description: identifier name for container
  github_token:
    description: token for github container registry
  environment:
    description: environment name
  image:
    description: docker image URL
  server_port:
    description: server port opened by docker
  app_port:
    description: app port used in docker
    default: '3000'
  additional_env:
    description: additional environment variables
    default: ''
runs:
  using: 'composite'
  steps:
    - id: env
      name: create .env 
      shell: bash
      run: |
        cat .github/environments/.env.${{ inputs.environment }} > .env
        echo ${{ inputs.additional_env }} >> .env
    - id: login
      name: login to Github Container Registry
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - id: run
      name: run docker compose
      shell: bash
      run: |
        docker pull ${{ inputs.image }}
        docker rm -f ${{ inputs.container_name }} || true
        docker run -d --name ${{ inputs.container_name }} --env-file .env -p ${{ inputs.server_port }}:${{ inputs.app_port }} --restart unless-stopped ${{ inputs.image }}
        docker system prune -a -f
    